// lib/revenue/services/rates-proof-renderer.ts
// Renders tenant proof as HTML document

import type { TenantProofData } from './rates-proof-generator';

export function renderProofHTML(proof: TenantProofData): string {
  const format = (n: number) => `R${n.toLocaleString('en-ZA', { minimumFractionDigits: 2 })}`;
  const pct = (n: number) => `${(n * 100).toFixed(2)}%`;

  return `
<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>Rates Recovery Proof</title>
<style>
  body { font-family: -apple-system, sans-serif; max-width: 700px; margin: 40px auto; color: #1a1a1a; line-height: 1.6; }
  h1 { font-size: 18px; border-bottom: 2px solid #1a1a1a; padding-bottom: 8px; }
  h2 { font-size: 14px; margin-top: 24px; }
  table { width: 100%; border-collapse: collapse; margin: 12px 0; font-size: 13px; }
  th { text-align: left; background: #f5f5f5; padding: 8px; font-size: 11px; text-transform: uppercase; letter-spacing: 0.5px; }
  td { padding: 8px; border-bottom: 1px solid #e5e5e5; }
  .total { font-weight: bold; border-top: 2px solid #1a1a1a; }
  .footer { margin-top: 40px; font-size: 10px; color: #999; text-align: center; }
  .badge { display: inline-block; background: #f0f0f0; padding: 2px 8px; border-radius: 4px; font-size: 11px; }
</style></head><body>

<h1>Rates &amp; Taxes Recovery — ${proof.property_name}</h1>
<p><strong>Tenant:</strong> ${proof.tenant_name} &nbsp;|&nbsp; <strong>Shop:</strong> ${proof.shop_number}</p>
<p><strong>Effective:</strong> ${proof.effective_date}</p>

<h2>Municipal Rates Change</h2>
<table>
  <tr><td>Previous Monthly Rates</td><td style="text-align:right">${format(proof.previous_monthly_rates)}</td></tr>
  <tr><td>New Monthly Rates</td><td style="text-align:right">${format(proof.new_monthly_rates)}</td></tr>
  <tr class="total"><td>Monthly Increase</td><td style="text-align:right">${format(proof.monthly_increase)}</td></tr>
</table>

<h2>Your Allocation</h2>
<table>
  <tr><td>Building Total GLA</td><td style="text-align:right">${proof.total_gla.toFixed(2)} m²</td></tr>
  <tr><td>Your GLA</td><td style="text-align:right">${proof.tenant_gla.toFixed(2)} m²</td></tr>
  <tr><td>Your Share</td><td style="text-align:right">${pct(proof.gla_percentage)}</td></tr>
</table>

<h2>Your Recovery Calculation</h2>
<table>
  <tr><td>Previous Monthly Recovery</td><td style="text-align:right">${format(proof.previous_monthly_charge)}</td></tr>
  <tr><td>Monthly Increase</td><td style="text-align:right">${format(proof.monthly_increase)}</td></tr>
  <tr class="total"><td>New Monthly Recovery</td><td style="text-align:right">${format(proof.new_monthly_charge)}</td></tr>
</table>

<p><span class="badge">${proof.back_charge_description}: ${format(proof.back_charge_amount)}</span></p>

${proof.documents.length > 0 ? `
<h2>Supporting Evidence</h2>
<p style="font-size:12px;color:#666">The following documents support this calculation:</p>
<ul style="font-size:12px">
  ${proof.documents.map(d => `<li>${d.document_type}: ${d.file_name}</li>`).join('')}
</ul>
` : ''}

<div class="footer">Generated by AssetFlow — Commercial Property Operating System</div>
</body></html>`;
}
