'use client';
import { useState, useEffect } from 'react';
import { supabase } from '@/lib/supabase';
export default function BanksPage() {
  const [banks, setBanks] = useState<any[]>([]);
  const [entityId, setEntityId] = useState('');
  const [showAdd, setShowAdd] = useState(false);
  const [form, setForm] = useState({ bank_name: '', account_name: '', account_number: '', branch_code: '', account_type: 'operating' });
  useEffect(() => { async function init() { const { data: { session } } = await supabase.auth.getSession(); if (!session) return; const { data: entities } = await supabase.rpc('auth_entities'); if (!entities?.length) return; setEntityId(entities[0]); const { data } = await supabase.from('bank_accounts').select('*').eq('entity_id', entities[0]); setBanks(data || []); } init(); }, []);
  async function handleAdd() { await supabase.from('bank_accounts').insert({ ...form, entity_id: entityId, is_active: true }); setShowAdd(false); const { data } = await supabase.from('bank_accounts').select('*').eq('entity_id', entityId); setBanks(data || []); }
  return (<div className="space-y-6"><div className="flex items-center justify-between"><h1 className="text-2xl font-light tracking-[-0.02em] text-white">Banks</h1><button onClick={() => setShowAdd(true)} className="rounded-lg bg-white px-4 py-2 text-xs font-medium text-black hover:bg-gray-100">+ Add</button></div><div className="rounded-xl border border-white/[0.06] overflow-hidden"><table className="w-full text-sm"><thead><tr className="border-b border-white/[0.06] bg-white/[0.02]"><th className="text-left py-3 px-4 text-[11px] font-medium text-zinc-500 uppercase">Bank</th><th className="text-left py-3 px-4 text-[11px] font-medium text-zinc-500 uppercase">Account</th><th className="text-left py-3 px-4 text-[11px] font-medium text-zinc-500 uppercase">Number</th></tr></thead><tbody>{banks.map(b => (<tr key={b.id} className="border-b border-white/[0.03]"><td className="py-2.5 px-4 text-white font-light">{b.bank_name}</td><td className="py-2.5 px-4 text-zinc-400">{b.account_name}</td><td className="py-2.5 px-4 text-zinc-400">{b.account_number}</td></tr>))}</tbody></table></div>{showAdd && <><div className="fixed inset-0 z-40 bg-black/60 backdrop-blur-sm" onClick={() => setShowAdd(false)} /><div className="fixed inset-4 z-50 flex items-center justify-center p-4"><div className="bg-zinc-950 border border-white/[0.08] rounded-2xl p-6 w-full max-w-md"><div className="flex justify-between items-center mb-4"><p className="text-sm font-medium text-white">Add Bank</p><button onClick={() => setShowAdd(false)} className="text-zinc-500 hover:text-white">✕</button></div><div className="space-y-3"><input value={form.bank_name} onChange={(e) => setForm({ ...form, bank_name: e.target.value })} placeholder="Bank Name" className="w-full rounded-lg border border-white/[0.08] bg-zinc-900 px-3 py-2.5 text-sm text-white outline-none" /><input value={form.account_name} onChange={(e) => setForm({ ...form, account_name: e.target.value })} placeholder="Account Name" className="w-full rounded-lg border border-white/[0.08] bg-zinc-900 px-3 py-2.5 text-sm text-white outline-none" /><input value={form.account_number} onChange={(e) => setForm({ ...form, account_number: e.target.value })} placeholder="Account Number" className="w-full rounded-lg border border-white/[0.08] bg-zinc-900 px-3 py-2.5 text-sm text-white outline-none" /><input value={form.branch_code} onChange={(e) => setForm({ ...form, branch_code: e.target.value })} placeholder="Branch Code" className="w-full rounded-lg border border-white/[0.08] bg-zinc-900 px-3 py-2.5 text-sm text-white outline-none" /><button onClick={handleAdd} className="w-full rounded-lg bg-white py-2.5 text-sm font-medium text-black hover:bg-gray-100">Add</button></div></div></div></>}</div>); }
