'use client';

import { useState, useEffect } from 'react';
import { Search, CheckSquare, AlertTriangle, Clock, Flag, Calendar } from "lucide-react";
import { Receipt, Landmark, MessageSquare, FileText, Briefcase, Shield, Settings } from "lucide-react";

export default function TasksPage() {
  const [data, setData] = useState<any>({ tasks: [], total: 0, summary: null });
  const [loading, setLoading] = useState(true);
  const [searchTerm, setSearchTerm] = useState("");
  const [filter, setFilter] = useState("all");
  const [page, setPage] = useState(0);
  const pageSize = 50;
  const [currentUser, setCurrentUser] = useState("");
  


  useEffect(() => { loadData(); }, [page, filter, searchTerm]);

  async function loadData() {
        setLoading(true);
    const params = new URLSearchParams({ page: String(page), pageSize: String(pageSize), filter });
    if (searchTerm) params.set("search", searchTerm);
    const res = await fetch(`/api/intelligence/tasks?${params}`);
    const json = await res.json();
    setData(json);
    setLoading(false);
  }

  const { tasks, total, summary } = data;
  const totalPages = Math.ceil(total / pageSize);

  const formatDate = (d: string) => d ? new Date(d).toLocaleDateString("en-ZA", { day: "numeric", month: "short" }) : "—";

  const priorityBadge = (priority: string) => {
    if (priority === 'Critical' || priority === 'High') return <Flag className="w-3 h-3 text-red-400" />;
    if (priority === 'Medium') return <Flag className="w-3 h-3 text-amber-400" />;
    return <Flag className="w-3 h-3 text-[var(--text-muted)]" />;
  };

  const statusBadge = (status: string, dueDate: string) => {
  if (status === "Completed") {
    return (
      <span className="text-xs px-2 py-0.5 rounded-full bg-emerald-500/10 text-emerald-300">
        Done
      </span>
    );
  }

  if (dueDate) {
    const due = new Date(dueDate);
    const today = new Date();

    const dueDay = due.toISOString().split("T")[0];
    const todayDay = today.toISOString().split("T")[0];

    if (dueDay < todayDay) {
      return (
        <span className="text-xs px-2 py-0.5 rounded-full bg-red-500/10 text-red-300">
          Overdue
        </span>
      );
    }

    if (dueDay === todayDay) {
      return (
        <span className="text-xs px-2 py-0.5 rounded-full bg-amber-500/10 text-amber-300">
          Today
        </span>
      );
    }
  }

  return (
    <span className="text-xs px-2 py-0.5 rounded-full bg-blue-500/10 text-blue-300">
      {status || "Open"}
    </span>
  );
};


const sourceIcon = (source: string) => {
  const s = (source || '').toLowerCase();
  if (s.includes('revenue') || s.includes('billing')) return <Receipt className="w-3 h-3 text-[var(--text-muted)]" />;
  if (s.includes('cash') || s.includes('bank') || s.includes('allocation')) return <Landmark className="w-3 h-3 text-[var(--text-muted)]" />;
  if (s.includes('comm') || s.includes('whatsapp') || s.includes('email')) return <MessageSquare className="w-3 h-3 text-[var(--text-muted)]" />;
  if (s.includes('lease')) return <FileText className="w-3 h-3 text-[var(--text-muted)]" />;
  if (s.includes('supplier')) return <Briefcase className="w-3 h-3 text-[var(--text-muted)]" />;
  if (s.includes('complian')) return <Shield className="w-3 h-3 text-[var(--text-muted)]" />;
  return <CheckSquare className="w-3 h-3 text-[var(--text-muted)]" />;
};

  const filters = [
  { key: "all", label: "All", count: summary?.total || 0 },
  { key: "my", label: "My Work", count: summary?.open || 0 },
  { key: "pending", label: "Open", count: summary?.open || 0 },
  { key: "overdue", label: "Overdue", count: summary?.overdue || 0 },
  { key: "today", label: "Today", count: summary?.today || 0 },
  { key: "high", label: "High Priority", count: summary?.high || 0 },
  {
    key: "completed",
    label: "Done",
    count: (summary?.total || 0) - (summary?.open || 0),
  },
];

  return (
    <div className="mx-auto max-w-7xl space-y-6 px-6 pt-8 pb-12">
      <div>
       <h1 className="text-2xl font-bold text-[var(--text-primary)]">Tasks</h1>
<p className="text-xs text-[var(--text-muted)] mt-1">Tasks generated by platform workflows and operational events.</p>
<p className="text-xs text-[var(--text-muted)]">{summary?.open || 0} open · {summary?.overdue || 0} overdue · {summary?.today || 0} due today · {summary?.high || 0} high priority</p>
      </div>

      {/* KPIs */}
      {summary && (
        <div className="grid grid-cols-5 gap-3">
          <div className="rounded-xl border border-[var(--border-default)] bg-[var(--bg-secondary)] p-3 text-center"><p className="text-lg font-bold text-[var(--text-primary)]">{summary.open}</p><p className="text-xs text-[var(--text-muted)]">Open</p></div>
          <div className="rounded-xl border border-[var(--border-default)] bg-[var(--bg-secondary)] p-3 text-center"><p className="text-lg font-bold text-red-400">{summary.overdue}</p><p className="text-xs text-[var(--text-muted)]">Overdue</p></div>
          <div className="rounded-xl border border-[var(--border-default)] bg-[var(--bg-secondary)] p-3 text-center"><p className="text-lg font-bold text-amber-400">{summary.today}</p><p className="text-xs text-[var(--text-muted)]">Due Today</p></div>
          <div className="rounded-xl border border-[var(--border-default)] bg-[var(--bg-secondary)] p-3 text-center"><p className="text-lg font-bold text-[var(--text-primary)]">{summary.high}</p><p className="text-xs text-[var(--text-muted)]">High Priority</p></div>
          <div className="rounded-xl border border-[var(--border-default)] bg-[var(--bg-secondary)] p-3 text-center"><p className="text-lg font-bold text-emerald-400">{summary.total - summary.open}</p><p className="text-xs text-[var(--text-muted)]">Completed</p></div>
        </div>
      )}

      {/* Search + Filters */}
      <div className="flex items-center gap-3 flex-wrap">
        <div className="relative flex-1 max-w-sm">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-[var(--text-muted)]" />
          <input type="text" value={searchTerm} onChange={(e) => { setSearchTerm(e.target.value); setPage(0); }} placeholder="Search tasks..." className="w-full rounded-xl border border-[var(--border-default)] bg-[var(--bg-secondary)] pl-10 pr-4 py-2.5 text-sm outline-none focus:border-[var(--border-hover)]" />
        </div>
        <div className="flex gap-2 flex-wrap">
          {filters.map(f => (
            <button key={f.key} onClick={() => { setFilter(f.key); setPage(0); }} className={`rounded-full px-4 py-1.5 text-xs font-medium transition-colors ${filter === f.key ? 'bg-[var(--text-primary)] text-[var(--bg-primary)]' : 'border border-[var(--border-default)] text-[var(--text-secondary)] hover:border-[var(--border-hover)]'}`}>
              {f.label} <span className="ml-1 opacity-60">{f.count}</span>
            </button>
          ))}
        </div>
      </div>

      {/* Table */}
      {loading ? (
        <div className="space-y-2">{[1,2,3,4,5].map(i => (<div key={i} className="rounded-xl border border-[var(--border-default)] bg-[var(--bg-secondary)] p-4 animate-pulse"><div className="h-4 bg-[var(--bg-elevated)] rounded w-1/3 mb-2"></div><div className="h-3 bg-[var(--bg-elevated)] rounded w-1/2"></div></div>))}</div>
      ) : tasks.length === 0 ? (
        <div className="text-center py-12 text-[var(--text-muted)]"><CheckSquare className="w-8 h-8 mx-auto mb-2 opacity-30" /><p>No tasks found</p></div>
      ) : (
        <>
          <div className="rounded-2xl border border-[var(--border-default)] bg-[var(--bg-secondary)] overflow-hidden">
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b border-[var(--border-default)]">
                  <th className="text-left py-2.5 px-4 text-xs text-[var(--text-muted)] font-normal uppercase tracking-[0.2em] w-8"></th>
                  <th className="text-left py-2.5 px-4 text-xs text-[var(--text-muted)] font-normal uppercase tracking-[0.2em]">Task</th>
                  <th className="text-left py-2.5 px-4 text-xs text-[var(--text-muted)] font-normal uppercase tracking-[0.2em]">Source</th>
                  <th className="text-left py-2.5 px-4 text-xs text-[var(--text-muted)] font-normal uppercase tracking-[0.2em]">Assigned</th>
                  <th className="text-left py-2.5 px-4 text-xs text-[var(--text-muted)] font-normal uppercase tracking-[0.2em]">Due</th>
                  <th className="text-left py-2.5 px-4 text-xs text-[var(--text-muted)] font-normal uppercase tracking-[0.2em]">Status</th>
                </tr>
              </thead>
              <tbody>
                {tasks.map((t: any) => (
                  <tr key={t.id} className="border-b border-[var(--border-default)] last:border-0 hover:bg-[var(--bg-elevated)] transition-colors">
                    <td className="py-2.5 px-4">{priorityBadge(t.priority)}</td>
                    <td className="py-2.5 px-4">
                      <div>
  <p className="text-[var(--text-primary)] font-medium">
    {t.task_type
      ? t.task_type.charAt(0).toUpperCase() + t.task_type.slice(1)
      : "Task"}
  </p>

  <p className="text-xs text-[var(--text-muted)] truncate max-w-xs">
    {t.task_id || "—"}
    {t.tenant_name ? ` · ${t.tenant_name}` : ""}
    {t.property_name ? ` · ${t.property_name}` : ""}
  </p>
</div>
                    </td>
                    <td className="py-2.5 px-4"><span className="flex items-center gap-1.5 text-xs text-[var(--text-secondary)]">{sourceIcon(t.task_type)} {t.task_type || "—"}</span></td>
                    <td className="py-2.5 px-4"><span className="text-xs text-[var(--text-muted)]">{t.assigned_to || "—"}</span></td>
                    <td className="py-2.5 px-4"><span className="text-xs text-[var(--text-muted)] flex items-center gap-1"><Calendar className="w-3 h-3" /> {formatDate(t.due_date)}</span></td>
                    <td className="py-2.5 px-4">{statusBadge(t.task_status, t.due_date)}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          {totalPages > 1 && (
            <div className="flex items-center justify-between">
              <div className="text-xs text-[var(--text-muted)]">Page {page + 1} of {totalPages}</div>
              <div className="flex items-center gap-1">
                <button onClick={() => setPage(p => Math.max(0, p - 1))} disabled={page === 0} className="px-3 py-1.5 rounded-lg text-xs hover:bg-[var(--bg-elevated)] disabled:opacity-30">← Prev</button>
                {Array.from({ length: Math.min(totalPages, 5) }, (_, i) => {
                  const start = Math.max(0, Math.min(page - 2, totalPages - 5));
                  const pageNum = start + i;
                  return <button key={pageNum} onClick={() => setPage(pageNum)} className={`w-8 h-8 rounded-lg text-xs font-medium transition-colors ${page === pageNum ? 'bg-[var(--text-primary)] text-[var(--bg-primary)]' : 'text-[var(--text-muted)] hover:bg-[var(--bg-elevated)]'}`}>{pageNum + 1}</button>;
                })}
                {totalPages > 5 && page < totalPages - 3 && <span className="text-xs text-[var(--text-muted)]">...{totalPages}</span>}
                <button onClick={() => setPage(p => Math.min(totalPages - 1, p + 1))} disabled={page >= totalPages - 1} className="px-3 py-1.5 rounded-lg text-xs hover:bg-[var(--bg-elevated)] disabled:opacity-30">Next →</button>
              </div>
            </div>
          )}
        </>
      )}
    </div>
  );
}
