import {
  Users,
  Building2,
  FileText,
  Receipt,
  Landmark,
  MessageSquare,
  Briefcase,
  Calendar,
  Upload,
  Settings,
  CheckSquare,
  TrendingDown,
  Clock,
  Timer,
  Activity,
  ShieldCheck,
  Search,
} from "lucide-react";

export const searchIcons: Record<string, any> = {
  tenant: Users,
  property: Building2,
  lease: FileText,
  statement: Receipt,
  invoice: Receipt,
  cashbook: Landmark,
  communication: MessageSquare,
  supplier: Briefcase,
  period: Calendar,
  import: Upload,
  settings: Settings,
  task: CheckSquare,
  revenue: Receipt,
  home: Activity,
};

export const sidebarIcons: Record<string, any> = {
  home: Activity,
  leases: FileText,
  revenue: Receipt,
  cashbook: Landmark,
  communications: MessageSquare,
  tasks: CheckSquare,
  properties: Building2,
  tenants: Users,
  suppliers: Briefcase,
  imports: Upload,
  periods: Calendar,
  settings: Settings,
};
