// lib/platform/validation/rules/lease.rules.ts
// Lease Validation Rules

import { ValidationRule } from '../types';

export const leaseRules: ValidationRule[] = [
  {
    id: 'lease.tenant_id',
    name: 'Tenant Required',
    description: 'A tenant must be selected for the lease',
    domain: 'lease',
    severity: 'critical',
    field: 'tenant_id',
    label: 'Tenant',
    operator: 'is_not_empty',
    message: 'A tenant is required for this lease',
    requires_approval: false,
    is_active: true,
    priority: 1,
  },
  {
    id: 'lease.property_id',
    name: 'Property Required',
    description: 'A property must be selected for the lease',
    domain: 'lease',
    severity: 'critical',
    field: 'property_id',
    label: 'Property',
    operator: 'is_not_empty',
    message: 'A property is required for this lease',
    requires_approval: false,
    is_active: true,
    priority: 1,
  },
  {
    id: 'lease.unit_id',
    name: 'Unit Required',
    description: 'A unit must be selected for the lease',
    domain: 'lease',
    severity: 'critical',
    field: 'unit_id',
    label: 'Unit',
    operator: 'is_not_empty',
    message: 'A unit is required for this lease',
    requires_approval: false,
    is_active: true,
    priority: 1,
  },
  {
    id: 'lease.monthly_rental',
    name: 'Monthly Rental Required',
    description: 'The monthly rental amount must be set',
    domain: 'lease',
    severity: 'critical',
    field: 'monthly_rental',
    label: 'Monthly Rental',
    operator: 'gt',
    value: 0,
    message: 'The monthly rental amount must be greater than R0',
    requires_approval: false,
    is_active: true,
    priority: 1,
  },
  {
    id: 'lease.deposit_amount',
    name: 'Deposit Required',
    description: 'A deposit amount must be set',
    domain: 'lease',
    severity: 'critical',
    field: 'deposit_amount',
    label: 'Deposit',
    operator: 'gt',
    value: 0,
    message: 'A deposit amount is required for this lease',
    requires_approval: false,
    is_active: true,
    priority: 1,
  },
  {
    id: 'lease.commencement_date',
    name: 'Commencement Date Required',
    description: 'The commencement date must be set',
    domain: 'lease',
    severity: 'critical',
    field: 'commencement_date',
    label: 'Commencement Date',
    operator: 'is_not_empty',
    message: 'A commencement date is required',
    requires_approval: false,
    is_active: true,
    priority: 1,
  },
  {
    id: 'lease.lease_term_months',
    name: 'Lease Term Required',
    description: 'The lease term must be set',
    domain: 'lease',
    severity: 'critical',
    field: 'lease_term_months',
    label: 'Lease Term',
    operator: 'gt',
    value: 0,
    message: 'A lease term is required',
    requires_approval: false,
    is_active: true,
    priority: 1,
  },
  {
    id: 'lease.contact_email',
    name: 'Contact Email',
    description: 'The contact email should be valid',
    domain: 'lease',
    severity: 'warning',
    field: 'contact_email',
    label: 'Contact Email',
    operator: 'email',
    message: 'The contact email should be a valid email address',
    requires_approval: false,
    is_active: true,
    priority: 2,
  },
  {
    id: 'lease.contact_phone',
    name: 'Contact Phone',
    description: 'The contact phone should be valid',
    domain: 'lease',
    severity: 'warning',
    field: 'contact_phone',
    label: 'Contact Phone',
    operator: 'phone',
    message: 'The contact phone should be a valid phone number',
    requires_approval: false,
    is_active: true,
    priority: 2,
  },
  {
    id: 'lease.applicant_name',
    name: 'Applicant Name',
    description: 'The applicant name should be set',
    domain: 'lease',
    severity: 'warning',
    field: 'applicant_name',
    label: 'Applicant Name',
    operator: 'is_not_empty',
    message: 'Applicant name is recommended',
    requires_approval: false,
    is_active: true,
    priority: 2,
  },
  {
    id: 'lease.company_registration',
    name: 'Company Registration',
    description: 'Company registration is recommended',
    domain: 'lease',
    severity: 'recommendation',
    field: 'company_registration',
    label: 'Company Registration',
    operator: 'is_not_empty',
    message: 'Company registration is recommended',
    requires_approval: false,
    is_active: true,
    priority: 3,
  },
];
