// lib/platform/validation/rules/supplier.rules.ts
// Supplier Validation Rules

import { ValidationRule } from '../types';

export const supplierRules: ValidationRule[] = [
  {
    id: 'supplier.name',
    name: 'Supplier Name Required',
    description: 'A name is required for the supplier',
    domain: 'supplier',
    severity: 'critical',
    field: 'name',
    label: 'Name',
    operator: 'is_not_empty',
    message: 'A supplier name is required',
    requires_approval: false,
    is_active: true,
    priority: 1,
  },
  {
    id: 'supplier.registration_number',
    name: 'Registration Number',
    description: 'Registration number is recommended',
    domain: 'supplier',
    severity: 'recommendation',
    field: 'registration_number',
    label: 'Registration Number',
    operator: 'is_not_empty',
    message: 'Supplier registration number is recommended',
    requires_approval: false,
    is_active: true,
    priority: 2,
  },
  {
    id: 'supplier.contact_person',
    name: 'Contact Person',
    description: 'A contact person is recommended',
    domain: 'supplier',
    severity: 'recommendation',
    field: 'contact_person',
    label: 'Contact Person',
    operator: 'is_not_empty',
    message: 'A contact person is recommended',
    requires_approval: false,
    is_active: true,
    priority: 2,
  },
  {
    id: 'supplier.insurance_verified',
    name: 'Insurance Required',
    description: 'Valid insurance is required for suppliers',
    domain: 'supplier',
    severity: 'warning',
    field: 'insurance_verified',
    label: 'Insurance Status',
    operator: 'eq',
    value: true,
    message: 'Supplier insurance verification is required before payment',
    requires_approval: false,
    reminder_days: 30,
    is_active: true,
    priority: 2,
  },
  {
    id: 'supplier.fica_verified',
    name: 'FICA Required',
    description: 'FICA verification is required for payment',
    domain: 'supplier',
    severity: 'critical',
    field: 'fica_verified',
    label: 'FICA Status',
    operator: 'eq',
    value: true,
    message: 'FICA verification is required before payment',
    requires_approval: true,
    approval_role: 'finance',
    reminder_days: 14,
    is_active: true,
    priority: 1,
  },
  {
    id: 'supplier.bank_details',
    name: 'Bank Details',
    description: 'Bank details are required for payment',
    domain: 'supplier',
    severity: 'critical',
    field: 'bank_account_number',
    label: 'Bank Account',
    operator: 'is_not_empty',
    message: 'Bank details are required for payment processing',
    requires_approval: false,
    reminder_days: 7,
    is_active: true,
    priority: 1,
  },
  {
    id: 'supplier.email',
    name: 'Email',
    description: 'A valid email is recommended',
    domain: 'supplier',
    severity: 'recommendation',
    field: 'email',
    label: 'Email',
    operator: 'email',
    message: 'A valid email address is recommended',
    requires_approval: false,
    is_active: true,
    priority: 3,
  },
  {
    id: 'supplier.phone',
    name: 'Phone',
    description: 'A valid phone number is recommended',
    domain: 'supplier',
    severity: 'recommendation',
    field: 'phone',
    label: 'Phone',
    operator: 'phone',
    message: 'A valid phone number is recommended',
    requires_approval: false,
    is_active: true,
    priority: 3,
  },
];
