// lib/platform/validation/rules/work-order.rules.ts
// Work Order Validation Rules

import { ValidationRule } from '../types';

export const workOrderRules: ValidationRule[] = [
  {
    id: 'work_order.title',
    name: 'Title Required',
    description: 'A title is required for the work order',
    domain: 'work_order',
    severity: 'critical',
    field: 'title',
    label: 'Title',
    operator: 'is_not_empty',
    message: 'A work order title is required',
    requires_approval: false,
    is_active: true,
    priority: 1,
  },
  {
    id: 'work_order.property_id',
    name: 'Property Required',
    description: 'A property is required for the work order',
    domain: 'work_order',
    severity: 'critical',
    field: 'property_id',
    label: 'Property',
    operator: 'is_not_empty',
    message: 'A property is required for this work order',
    requires_approval: false,
    is_active: true,
    priority: 1,
  },
  {
    id: 'work_order.priority',
    name: 'Priority Required',
    description: 'Priority must be set for the work order',
    domain: 'work_order',
    severity: 'critical',
    field: 'priority',
    label: 'Priority',
    operator: 'is_not_empty',
    message: 'Work order priority is required',
    requires_approval: false,
    is_active: true,
    priority: 1,
  },
  {
    id: 'work_order.assigned_to',
    name: 'Supplier Assignment',
    description: 'A supplier should be assigned to the work order',
    domain: 'work_order',
    severity: 'warning',
    field: 'assigned_to',
    label: 'Assigned Supplier',
    operator: 'is_not_empty',
    message: 'Assigning a supplier is recommended',
    requires_approval: false,
    reminder_days: 3,
    is_active: true,
    priority: 2,
  },
  {
    id: 'work_order.description',
    name: 'Description',
    description: 'A description is recommended',
    domain: 'work_order',
    severity: 'warning',
    field: 'description',
    label: 'Description',
    operator: 'is_not_empty',
    message: 'A description is recommended',
    requires_approval: false,
    is_active: true,
    priority: 2,
  },
  {
    id: 'work_order.estimated_cost',
    name: 'Estimated Cost',
    description: 'An estimated cost is recommended',
    domain: 'work_order',
    severity: 'recommendation',
    field: 'estimated_cost',
    label: 'Estimated Cost',
    operator: 'gt',
    value: 0,
    message: 'An estimated cost is recommended',
    requires_approval: false,
    is_active: true,
    priority: 3,
  },
];
