import { lodRenderer } from './lod-renderer';

export async function printLOD(tenantId: string, templateId: string, entityId: string) {
  const result = await lodRenderer.render(tenantId, templateId, entityId);
  const printWindow = window.open('', '_blank');
  if (printWindow) {
    printWindow.document.write(`<!DOCTYPE html><html><head><meta charset="utf-8"><title>${result.subject}</title><style>body{font-family:Arial,sans-serif;padding:40px;color:#1a1a1a;line-height:1.6;font-size:12pt;}@media print{body{padding:20px;}}</style></head><body>${result.html}<p style="margin-top:40px;font-size:8pt;color:#999;">Generated by AssetFlow — ${new Date().toLocaleString('en-ZA')}</p></body></html>`);
    printWindow.document.close();
    printWindow.print();
  }
}
