export type LeaseTemplateStatus =
  | 'draft'
  | 'active'
  | 'archived';

export type LeaseTemplateReviewStatus =
  | 'pending'
  | 'in_review'
  | 'approved'
  | 'rejected';

export type LeaseTemplateCategory =
  | 'industrial'
  | 'retail'
  | 'office'
  | 'residential'
  | 'commercial'
  | 'informal'
  | 'other';

export type LeaseTemplateAnalysisMode =
  | 'blank_template'
  | 'completed_example';

export type LeaseTemplateFieldType =
  | 'text'
  | 'number'
  | 'currency'
  | 'date'
  | 'percentage'
  | 'email'
  | 'phone'
  | 'boolean';

export type LeaseTemplateTargetKind =
  | 'placeholder'
  | 'docx_text'
  | 'docx_table_cell'
  | 'docx_content_control'
  | 'docx_bookmark'
  | 'pdf_form_field'
  | 'pdf_region';

export type LeaseTemplateMappingStatus =
  | 'suggested'
  | 'confirmed'
  | 'rejected'
  | 'unresolved';

export type LeaseTemplateSuggestionSeverity =
  | 'info'
  | 'warning'
  | 'critical';

export type LeaseTemplateSuggestionType =
  | 'field'
  | 'clause'
  | 'inconsistency'
  | 'warning';

export interface LeaseTemplateBoundingBox {
  x: number;
  y: number;
  width: number;
  height: number;
}

export interface LeaseTemplateFieldEvidence {
  text: string;
  page?: number;
  startOffset?: number;
  endOffset?: number;
  boundingBox?: LeaseTemplateBoundingBox;

  /*
   * Optional structural information for document formats where
   * page coordinates alone are not a stable insertion target.
   */
  structuralPath?: string;
}

export interface LeaseTemplateMappingConfidence {
  /*
   * Confidence that the source content itself was read correctly.
   */
  ocr?: number;

  /*
   * Confidence that AssetFlow identified the correct document target.
   */
  detection?: number;

  /*
   * Confidence that the document target maps to the proposed
   * canonical AssetFlow field.
   */
  mapping?: number;

  /*
   * Confidence in an extracted example value, when a completed
   * example document is being analysed.
   */
  extraction?: number;
}

export interface LeaseTemplateDocumentTarget {
  kind: LeaseTemplateTargetKind;

  /*
   * Stable identifier for this target within the template version.
   * This may initially be generated by AssetFlow and later become
   * format-specific as structural parsers are introduced.
   */
  targetId: string;

  /*
   * Original placeholder/token/field name where one exists.
   */
  token?: string;

  /*
   * Human-readable source text associated with the target.
   */
  sourceText?: string;

  page?: number;
  startOffset?: number;
  endOffset?: number;
  boundingBox?: LeaseTemplateBoundingBox;

  /*
   * Format-specific structural location.
   *
   * Examples:
   * - DOCX paragraph/run path
   * - DOCX table row/cell path
   * - content-control identifier
   * - bookmark name
   * - PDF AcroForm field name
   */
  structuralPath?: string;

  /*
   * Format-specific metadata that is useful for generation but
   * should not be promoted into the common contract.
   */
  metadata?: Record<string, unknown>;
}

export interface LeaseTemplateFieldMapping {
  /*
   * Stable identity for the mapping within this template version.
   */
  id: string;

  /*
   * Canonical AssetFlow field key.
   *
   * Existing keys such as tenant_name are intentionally retained
   * during the first migration step. Canonical-key evolution is a
   * separate controlled migration.
   */
  fieldKey: string;

  label: string;
  type: LeaseTemplateFieldType;
  required: boolean;

  /*
 * Exact insertion target in the customer's source document.
 *
 * This is intentionally optional while a mapping is unresolved.
 * A mapping must not become confirmed or approved until a valid
 * target has been identified and reviewed.
 */
target?: LeaseTemplateDocumentTarget;

  status: LeaseTemplateMappingStatus;

  confidence?: LeaseTemplateMappingConfidence;

  evidence?: LeaseTemplateFieldEvidence[];

  /*
   * Example value discovered from a populated lease. This is
   * evidence used during mapping review; it is NOT the reusable
   * value that will be inserted into future leases.
   */
  exampleValue?: unknown;

  source?: 'system' | 'user' | 'ai';

  approved?: boolean;
  approvedBy?: string | null;
  approvedAt?: string | null;

  /*
   * Optional generation instructions for this target.
   * These remain intentionally generic until the DOCX/PDF
   * generation engines establish their exact contracts.
   */
  formatting?: Record<string, unknown>;
}

export interface LeaseTemplateAISuggestion {
  id?: string;
  type: LeaseTemplateSuggestionType;
  title: string;
  description: string;
  severity: LeaseTemplateSuggestionSeverity;

  fieldKey?: string;
  mappingId?: string;
  target?: LeaseTemplateDocumentTarget;

  confidence?: LeaseTemplateMappingConfidence;
  evidence?: LeaseTemplateFieldEvidence[];
}

export interface LeaseTemplateClauseSuggestion {
  id?: string;

  /*
   * Canonical clause/rule identifier where AssetFlow recognises one.
   */
  clauseKey?: string;

  title: string;
  description: string;
  severity: LeaseTemplateSuggestionSeverity;

  sourceText?: string;
  confidence?: number;
  evidence?: LeaseTemplateFieldEvidence[];

  status?: LeaseTemplateMappingStatus;
}

/*
 * Represents a field/value discovered while analysing document content.
 *
 * This remains separate from LeaseTemplateFieldMapping because a value
 * extracted from a completed/example lease is not itself a reusable
 * template mapping.
 */
export interface LeaseTemplateField {
  key: string;
  label: string;
  type: LeaseTemplateFieldType;
  required: boolean;

  /*
   * Value extracted from an existing/completed example lease.
   * Blank templates are not required to provide a value.
   */
  value?: unknown;

  /*
   * Legacy aggregate confidence retained while existing producers
   * migrate to the dimensional confidence model.
   */
  confidence?: number;

  evidence?: LeaseTemplateFieldEvidence[];

  /*
   * Legacy field-level approval retained for compatibility during
   * migration. Reusable template approval will ultimately operate
   * on LeaseTemplateFieldMapping records.
   */
  approved?: boolean;

  placeholder?: string;
  source?: 'system' | 'user' | 'ai';
}

export interface LeaseTemplate {
  id: string;
  entity_id: string;

  family_id?: string | null;

  template_name: string;
  category: LeaseTemplateCategory;

  version: number;
  status: LeaseTemplateStatus;
  review_status: LeaseTemplateReviewStatus;

  source_document_id?: string | null;
  source_document_url?: string | null;
  source_document_checksum?: string | null;
  source_file_name?: string | null;
  source_mime_type?: string | null;

  /*
   * Existing extraction-oriented field collection.
   * Retained during migration so current analyser and review paths
   * remain compatible.
   */
  fields: LeaseTemplateField[];

  /*
   * Durable reusable mapping between AssetFlow fields and exact
   * locations/controls in this template version.
   */
  field_mapping?: LeaseTemplateFieldMapping[];

  ai_suggestions?: LeaseTemplateAISuggestion[];
  clause_suggestions?: LeaseTemplateClauseSuggestion[];

  property_ids?: string[];

  applies_to_property_types: string[];

  ai_enabled: boolean;

  created_by?: string | null;
  reviewed_by?: string | null;
  reviewed_at?: string | null;

  archived_by?: string | null;
  archived_at?: string | null;

  created_at: string;
  updated_at: string;
}