// lib/reporting/layout/engine.ts
export interface ReportHeader { companyLogo?: string; companyName: string; reportTitle: string; period?: string; filters?: string[]; generatedAt: string; }
export interface ReportFooter { companyName: string; generatedAt: string; pageNumber: number; totalPages: number; }
export interface ReportTable { headers: string[]; rows: string[][]; columnWidths?: number[]; totals?: string[]; }
export interface ReportLayout { header: ReportHeader; sections: { title?: string; table: ReportTable }[]; footer: ReportFooter; orientation: 'portrait' | 'landscape'; poweredBy: string; }
export function buildReportLayout(params: { companyName: string; companyLogo?: string; reportTitle: string; orientation: 'portrait' | 'landscape'; period?: string; filters?: string[]; sections: { title?: string; headers: string[]; rows: string[][]; totals?: string[] }[] }): ReportLayout {
  return { header: { companyLogo: params.companyLogo, companyName: params.companyName, reportTitle: params.reportTitle, period: params.period, filters: params.filters, generatedAt: new Date().toISOString() }, sections: params.sections.map(s => ({ title: s.title, table: { headers: s.headers, rows: s.rows, totals: s.totals } })), footer: { companyName: params.companyName, generatedAt: new Date().toISOString(), pageNumber: 1, totalPages: 1 }, orientation: params.orientation, poweredBy: 'Generated by AssetFlow — Commercial Property Operating System' };
}
