export type ReportCategory = 'financial' | 'operational' | 'tenant' | 'supplier' | 'maintenance' | 'executive';
export type ReportFormat = 'pdf' | 'excel' | 'csv';
export type ReportOrientation = 'portrait' | 'landscape';
export interface ReportDefinition { id: string; title: string; category: ReportCategory; orientation: ReportOrientation; paperSize: string; formats: ReportFormat[]; permission: string; description?: string; defaultFilename: string; supportsScheduling: boolean; supportsEmail: boolean; supportsMergedPack: boolean; supportsDrillDown: boolean; }
export const reportRegistry: ReportDefinition[] = [
  { id: 'trial-balance', title: 'Trial Balance', category: 'financial', orientation: 'landscape', paperSize: 'A4', formats: ['pdf', 'excel', 'csv'], permission: 'reports.view', defaultFilename: 'Trial-Balance', supportsScheduling: true, supportsEmail: true, supportsMergedPack: true, supportsDrillDown: true },
  { id: 'income-statement', title: 'Income Statement', category: 'financial', orientation: 'portrait', paperSize: 'A4', formats: ['pdf', 'excel', 'csv'], permission: 'reports.view', defaultFilename: 'Income-Statement', supportsScheduling: true, supportsEmail: true, supportsMergedPack: true, supportsDrillDown: true },
  { id: 'balance-sheet', title: 'Balance Sheet', category: 'financial', orientation: 'portrait', paperSize: 'A4', formats: ['pdf', 'excel', 'csv'], permission: 'reports.view', defaultFilename: 'Balance-Sheet', supportsScheduling: true, supportsEmail: true, supportsMergedPack: true, supportsDrillDown: true },
  { id: 'cash-flow', title: 'Cash Flow Statement', category: 'financial', orientation: 'portrait', paperSize: 'A4', formats: ['pdf', 'excel', 'csv'], permission: 'reports.view', defaultFilename: 'Cash-Flow', supportsScheduling: true, supportsEmail: true, supportsMergedPack: true, supportsDrillDown: true },
  { id: 'rent-roll', title: 'Rent Roll', category: 'operational', orientation: 'landscape', paperSize: 'A4', formats: ['pdf', 'excel', 'csv'], permission: 'reports.view', defaultFilename: 'Rent-Roll', supportsScheduling: true, supportsEmail: true, supportsMergedPack: true, supportsDrillDown: false },
  { id: 'aged-debtors', title: 'Aged Debtors', category: 'tenant', orientation: 'landscape', paperSize: 'A4', formats: ['pdf', 'excel', 'csv'], permission: 'reports.view', defaultFilename: 'Aged-Debtors', supportsScheduling: true, supportsEmail: true, supportsMergedPack: true, supportsDrillDown: false },
  { id: 'aged-creditors', title: 'Aged Creditors', category: 'supplier', orientation: 'landscape', paperSize: 'A4', formats: ['pdf', 'excel', 'csv'], permission: 'reports.view', defaultFilename: 'Aged-Creditors', supportsScheduling: true, supportsEmail: true, supportsMergedPack: true, supportsDrillDown: false },
];
export function getReport(id: string): ReportDefinition | undefined { return reportRegistry.find(r => r.id === id); }
export function getReportsByCategory(category: ReportCategory): ReportDefinition[] { return reportRegistry.filter(r => r.category === category); }
export const reportCategories: { key: ReportCategory; label: string }[] = [{ key: 'financial', label: 'Financial' }, { key: 'operational', label: 'Operational' }, { key: 'tenant', label: 'Tenant' }, { key: 'supplier', label: 'Supplier' }, { key: 'executive', label: 'Executive' }];
